### ISSUE TITLE
インラインアセンブラtips集: `memory` clobberの説明が欲しい

### ISSUE THREAD

**Issue by kubo39** [pasokonistan/pasopedia#17]
`memory` の説明がないので、どういう意味があるのかよくわかりませんでした！！
よくある `__asm__ __volatile__("": : :"memory")` を使ってreorderingを抑制(SW barrier)する話とかあるといいと思います！！

@Totsugekitai 先生よろしくお願いいたします！

**Comment by kubo39** [comment]
Rustのasm!構文を読んでみると、デフォルトで`memory` constraintを付与、かつoptionで `NOMEM` を指定することで外すことができるそうです。
https://doc.rust-lang.org/reference/inline-assembly.html#options

LLVM backendではこのような記述があるが、意図が汲めていない。
https://github.com/rust-lang/rust/blob/2f19122f73027219a152e0c2ff35cebab940876c/compiler/rustc_codegen_llvm/src/asm.rs#L268-L273
```rust
        if !options.contains(InlineAsmOptions::NOMEM) {
            // This is actually ignored by LLVM, but it's probably best to keep
            // it just in case. LLVM instead uses the ReadOnly/ReadNone
            // attributes on the call instruction to optimize.
            constraints.push("~{memory}".to_string());
        }
```

**Comment by Totsugekitai** [comment]
コメントありがとうございます、今週ちょっと忙しいのでもしかしたら遅くなるかもしれませんが、追記しておきたいと思います！

**Comment by kubo39** [comment]
Rust and Atomicsのcompiler fenceの説明ではLLVM固有の情報には触れていない: https://marabos.nl/atomics/memory-ordering.html#compiler-fences

ただどうもLLVMは現状compiler fenceをatomic fenceにloweringするようで、これを是正するパッチが出ている(まだ本体には取り込まれていない): https://reviews.llvm.org/D92842

**Comment by kubo39** [comment]
> LLVM backendではこのような記述があるが、意図が汲めていない。
https://github.com/rust-lang/rust/blob/2f19122f73027219a152e0c2ff35cebab940876c/compiler/rustc_codegen_llvm/src/asm.rs#L268-L273

すぐ下に説明があった。`~{memory}` の有無にかかわらずデフォルトで最適化を許容しないようになっているのだな。

https://github.com/rust-lang/rust/blob/2f19122f73027219a152e0c2ff35cebab940876c/compiler/rustc_codegen_llvm/src/asm.rs#L305-L316
```rust
        if options.contains(InlineAsmOptions::PURE) {
            if options.contains(InlineAsmOptions::NOMEM) {
                attrs.push(llvm::MemoryEffects::None.create_attr(self.cx.llcx));
            } else if options.contains(InlineAsmOptions::READONLY) {
                attrs.push(llvm::MemoryEffects::ReadOnly.create_attr(self.cx.llcx));
            }
            attrs.push(llvm::AttributeKind::WillReturn.create_attr(self.cx.llcx));
        } else if options.contains(InlineAsmOptions::NOMEM) {
            attrs.push(llvm::MemoryEffects::InaccessibleMemOnly.create_attr(self.cx.llcx));
        } else {
            // LLVM doesn't have an attribute to represent ReadOnly + SideEffect
        }
        attributes::apply_to_callsite(result, llvm::AttributePlace::Function, &{ attrs });
```

**Comment by kubo39** [comment]
readonly + sideeffectな最適化の組み合わせがLLVMでは提供できなくて、本来可能である最適化ができないっちゅう話かも。かなし～。

**Comment by kubo39** [comment]
結論だけ書くと、LLVMのインラインアセンブラはmemory clobber(`~{memory}`)を単に無視します。
かわりにclangやrustcなどの各処理系がいい感じに関数属性を設定(LLVMのインラインアセンブラはLLVM内部的には関数と同じ扱い)することで同等の機能を実現しています。
(ここまでpasopediaに書く必要はあるんだろうか…？)

**Comment by Totsugekitai** [comment]
これは驚きですね！この内容も追記していいですか？
（もちろん @kubo39 さんから教えて頂いたということを明記します）

**Comment by kubo39** [comment]
@Totsugekitai 
大丈夫です、というかここに書いてることは自由に使ってもらってかまわないですよ。

**Comment by Totsugekitai** [comment]
ありがとうございます🙇

**Comment by kubo39** [comment]
clobberでレジスタしかチェックしてなさそうな箇所のコード: https://github.com/llvm/llvm-project/blob/a134abf4be132cfff2fc5132d6226db919c0865b/llvm/lib/CodeGen/GlobalISel/InlineAsmLowering.cpp#L524-L537

**Comment by kubo39** [comment]
fixed at #18
