### ISSUE TITLE
`hugo server` で自分の書いた記事が表示されない

### ISSUE THREAD

**Issue by Totsugekitai** [pasokonistan/pasopedia#7]
試しに次の画像のように、 `/content/pages/GNOMEにおけるfcitx5+mozcの設定方法/_index.md` を生やしてみた。

![image](https://user-images.githubusercontent.com/37617413/232315946-db9e62e9-2e6a-4ff1-a91c-45034efe2df9.png)

しかし `hugo server` でサーバを起動してもページが見当たらない。

![image](https://user-images.githubusercontent.com/37617413/232316064-9f2f0d1b-0199-4313-9c4f-a5bfc3011ec8.png)

起動時のログは以下の通り。

```
$ hugo server
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1

                   | JA  
-------------------+-----
  Pages            | 15  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 78  
  Processed images |  0  
  Aliases          |  2  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 52 ms
Watching for changes in /home/totsugekitai/workspace/pasokonistan/pasopedia/{archetypes,assets,content,i18n,layouts,themes}
Watching for config changes in /home/totsugekitai/workspace/pasokonistan/pasopedia/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by sksat** [comment]
- Hugo が古い
- https://github.com/pasokonistan/pasopedia/blob/7453f9b3c29992d61731947e301bbe359026bae5/content/pages/_index.md?plain=1#L2 などがあるのがおかしそう？

とか思ったけど，こっちで試しても違いそう

**Comment by Totsugekitai** [comment]
> * https://github.com/pasokonistan/pasopedia/blob/7453f9b3c29992d61731947e301bbe359026bae5/content/pages/_index.md?plain=1#L2
>    などがあるのがおかしそう？

これがビンゴで、この値をfalseにしたら画像のように表示されました。

![image](https://user-images.githubusercontent.com/37617413/232321851-9a776398-b328-4364-a933-c52fa8871570.png)

**Comment by Totsugekitai** [comment]
https://handbook.brownfield.dev/company/handbook/#front-matter-options

> bookHidden: if set to true, hides the page from the left navigation

ナルホディウス

**Comment by Totsugekitai** [comment]
#9 にて解決。
